const redux = {
  API_SERVER_ERROR: 'API_SERVER_ERROR',
  AUTHENTICATION: {
    LOGIN: {
      FETCH: 'FETCH_AUTHENTICATION_LOGIN',
      RECEIVE: 'RECEIVE_AUTHENTICATION_LOGIN',
    },
    OTP: {
      FETCH: 'FETCH_AUTHENTICATION_OTP',
      RECEIVE: 'RECEIVE_AUTHENTICATION_OTP',
    },
    LOGOUT: {
      FETCH: 'FETCH_LOGOUT',
      RECEIVE: 'RECEIVE_LOGOUT',
    },
  },
};

export default redux;
