const redux = {
  API_SERVER_ERROR: 'API_SERVER_ERROR',
  RESET_REDUX: 'RESET_REDUX',
  AUTHENTICATION: {
    LOGIN: 'LOGIN',
    VERIFY_OTP: 'VERIFY_OTP',
    LOGOUT: 'LOGOUT',
    CHECK_TOKEN: 'CHECK_TOKEN',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
  },
};

export default redux;
