const redux = {
  API_SERVER_ERROR: 'API_SERVER_ERROR',
  RESET_REDUX: 'RESET_REDUX',
  AUTHENTICATION: {
    LOGIN: 'LOGIN',
    VERIFY_OTP: 'VERIFY_OTP',
    LOGOUT: 'LOGOUT',
    CHECK_TOKEN: 'CHECK_TOKEN',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
  },
  PASSWORD: {
    FORGOT: 'FORGOT_PASSWORD',
    CHANGE: 'CHANGE_PASSWORD',
  },
  REGISTRATION: {
    CHECK: 'CHECK_REGISTRATION',
    VERIFY_REGISTRATION: 'VERIFY_REGISTRATION',
  },
};

export default redux;
